### PR TITLE
Merge WarpX regression testing

### PR DESCRIPTION
**Pull request by lucafedeli88**
This PR should merge back into AMReX the version of regression testing developed for WarpX.

There are several relatively small additions in the WarpX version of regression testing. I have to confess that I am not completely sure about what all these additions actually do. However, I have listed them here:

-  **Hack to prevent tools from building** 
In `build_tools(self, test_list)`  (`suite.py`) the WarpX version of regression testing  contains a line `ftools = []` . It is commented as 
a hack to prevent tools from building. I don't know why WarpX needs this hack and I am not sure about the consequences...

- **Creation of a Bin directory**
The WarpX version of regression testing adds these lines to `regtest.py` in order to create a `Bin` directory:
```
        # Create directory for executables
        binDir = 'Bin'
        if not os.path.exists(binDir):
            os.mkdir(binDir) 
```
`binDir` is used in `test_suite` (`regtest.py`), where `needed_files.append((executable, "move"))` is replaced with `needed_files.append((os.path.join(binDir,executable), "copy"))` . Also, `executable` is copied to `binDir` : 
```
            if executable is not None:
                shutil.copy( executable, binDir )
```
- **Support for fortran**
There are several additions which concern fortran. For instance:
1. `ENV['FC']  = self.FCOMP`, `self.FCOMP = "gfortran"` and `self.add_to_f_make_command = ""` in `suite.py`
2. the new functions `get_comp_string_f` and `build_f` in `suite.py`
3. the code added under `elif suite.sourceTree == "F_Src" or test.testSrcTree == "F_Src":` in `test_suite` (`reg_test.py`), in the section responsible for code compilation

- **Log the execution time**
The following lines are added to `def_test_suite` in `regtest.py`
```
        #----------------------------------------------------------------------
        # Print execution time
        #----------------------------------------------------------------------
        suite.log.log("execution time: %.1fs" %test.wall_time)
```

- **New member variable**
A new member variable `self.executable` is added to `suite.py`

- **Change condition in `crashed`**
In `crashed` (`suite.py`) the return value is changed from
`len(self.backtrace) > 0 or (self.run_as_script and self.return_code != 0)`
to
`len(self.backtrace) > 0 or ((self.run_as_script or (not self.doComparison)) and self.return_code != 0)`

- **Print analysis error message**
The following lines are added to `test_suite` :
```
# Print analysis error message (useful for Travis tests)
with open(outfile) as f:
    print( f.read() )
```

- **Check for the existence of a path**
In `regtest.py` the line `shutil.copy("{}/{}.make.out".format(output_dir, test.name), suite.full_web_dir)` is replaced with an equivalent code which contains a check:
```
        outfile = "{}/{}.make.out".format(output_dir, test.name)
        if os.path.exists(outfile):
            shutil.copy(outfile, suite.full_web_dir)
```

- **Comparison with tolerance**
The following lines are added to `test_suite` in `regtest.py`:
```
# Comparison within tolerance - reliant on fvarnames and fcompare
elif test.tolerance is not None:
    vars = get_variable_names(suite, bench_file)
    test.compare_successful = process_comparison_results(sout, vars, test)
```

### CODE REVIEW

**Comment by MaxThevenet** [comment]
Great, thanks a lot for this PR @lucafedeli88! In general, WarpX forked this repo a few years ago and did some changes required for WarpX. The biggest one is to avoid recompiling as much as possible (so old executables are stored, and their names registered, to be able to re-use them later if needed), which explains a number of changes mentioned above by Luca.

To add a bit of context, we believe that these changes can be useful for the main AMReX repo. Besides, WarpX is interested in adding some functionality (for instance, the possibility to execute a Python script **before** running a test, typically to prepare some input file required for a test). Of the two options (i) let the WarpX fork diverge further from this repo or (ii) merge them if possible, this PR is one step in the direction of (ii). @zingale If this works for you, we will delete the WarpX fork when this PR is merged and contribute to `AMReX-Codes/regression_testing` directly in the future.

**Comment by zingale** [comment]
why do you need the Fortran support?  That was originally for FBoxLib -- is WarpX using FBoxLib?

**Comment by MaxThevenet** [comment]
Good point, we may not, we'll do some test.

**Comment by zingale** [comment]
I suspect that you forked from an old version of the script

**Comment by MaxThevenet** [comment]
The WarpX fork was created >3 years ago indeed, and we have been using it until now.

**Comment by RemiLehe** [comment]
@zingale I am responsible for many of these changes from 3 years ago, which, admittedly, are not very readable.
I'll separate them into different PR, with some more information in the PR description.

**Comment by zingale** [comment]
okay cool.

**Pull request closed without merging**
