### PR TITLE
Add AMReX_SPACEDIM flag to CMake configure step

### PR DESCRIPTION
**Pull request by BenWibking**
This adds `-DAMReX_SPACEDIM=` to the CMake configure step when building tests.

Closes https://github.com/AMReX-Codes/regression_testing/issues/138.

### CODE REVIEW

**Comment by zingale** [comment]
@ax3l is this change okay with you?

**Review by ax3l — APPROVED** [review]
Thanks, looks good!
We added this manually so far, but this is better :+1: 

https://github.com/ECP-WarpX/WarpX/blob/24.06/Regression/WarpX-tests.ini#L1857-L1859

**Comment by BenWibking** [comment]
> Oh, well, technically in CMake we delegate this to application code (e.g., `WarpX_DIMS`, `ImpactX_DIMS`), which then sets the option for AMReX in superbuilds, too.
> 
> This PR only sets `AMReX_SPACEDIM`, which we usually do _not_ user-configure from applications.

In Quokka, we set `AMReX_SPACEDIM` directly. Is this a reason to prefer setting another app-specific parameter instead, and then set AMReX_SPACEDIM in the app's CMakeList.txt?

**Comment by ax3l** [comment]
Yes, abstraction. AMReX can be pre-installed, with 3 different dims at a time. We might just want to build a specific dim or 2 out of three dims of our app.

**Comment by BenWibking** [comment]
Ah, ok. That makes sense. We have always done superbuilds.

But in any case, having a var to change the name of the dim parameter makes sense to me.

**Comment by ax3l** [comment]
Oops, should have removed approval. I think we should first add the extra option we mentioned

**Pull request merged**
