### PR TITLE
CMake: Extra Configs & Superbuilds

### PR DESCRIPTION
**Pull request by ax3l**
- [x] rebase after #90, #92, #93, #94 were merged

### CODE REVIEW

**Comment by ax3l** [comment]
@zingale ready for review/merge, too :)

**Review by zingale — APPROVED** [review]

**Comment by ax3l** [comment]
Note @WeiqunZhang et al.: please update CMake to 3.12+ so it supports `--parallel/-j` on your nightly runners.

Recommended: upgrade to CMake 3.18+ or 3.20+.

**Comment by ax3l** [comment]
Update: Garunda uses CMake 3.16.3 atm.

We are looking at a regression with MFix, let's check what's in `f'cmake --build {self.source_build_dir} -j {self.numMakeJobs} -- {opts} {target}'` for it :)

**Comment by WeiqunZhang** [comment]
The old command is `make -j8  all`, whereas the new command is `cmake --build  -j 8 --  all`.

**Comment by ax3l** [comment]
@WeiqunZhang did we solve this?

**Comment by WeiqunZhang** [comment]
No.  We probably just need to replace `{self.source_build_dir}` with `.`.

**Comment by ax3l** [comment]
Yep, or it should read `test.buildDir`, but we don't pass the `test` object in here yet. Thus, `.` should work, will post a PR.

**Comment by ax3l** [comment]
Yep, or it should read `test.buildDir`, but we don't pass the `test` object in here yet.
What is is setting in the per-test
```ini
[testName]
buildDir = .
```
?

**Pull request merged**
